# Site Settings
title: ballot
description: ""
email: snoliver@umich.edu
baseurl: "/"
githubusername: oliversno

# Build Settings
markdown: kramdown

# Sass Settings
exclude: [".sass-cache/", "_site/", "functions/", "node_modules/", ".firebaserc", "database.rules.json", "firebase.json"]
sass:
  sass_dir: sass
  style: compressed